### ISSUE TITLE
Error when trying to upload images using mapillary plugin

### ISSUE THREAD

**Issue by iamiriman** [JOSM/Mapillary#102]
Hello, when I try to upload images I get this error:

![image](https://user-images.githubusercontent.com/55899160/66551752-f31c2900-eb54-11e9-968c-e12c4bcd2a90.png)

I click keep plugin and then I get this:

<details>

```
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2019-09-29 23:59:43 +0200 (Sun, 29 Sep 2019)
Build-Date:2019-09-29 22:01:37
Revision:15390
Relative:URL: ^/trunk

Identification: JOSM/1.5 (15390 en) Windows 7 32-Bit
OS Build number: Windows 7 Ultimate (7601)
Memory Usage: 976 MB / 989 MB (372 MB allocated, but free)
Java version: 1.8.0_221-b11, Oracle Corporation, Java HotSpot(TM) Client VM
Screen: \Display0 1360x768
Maximum Screen Size: 1360x768
VM arguments: [-Djava.net.useSystemProxies=true]

Plugins:
+ AddrInterpolation (34908)
+ CADTools (1008)
+ DirectDownload (34977)
+ DirectUpload (35041)
+ DxfImport (1013)
+ EasyPresets (1537621333)
+ FastDraw (34977)
+ HouseNumberTaggingTool (34977)
+ ImportImagePlugin (35125)
+ InfoMode (34908)
+ Mapillary (1.5.19)
+ OpeningHoursEditor (34977)
+ PicLayer (35104)
+ PolygonCutOut (v0.7)
+ ShapeTools (1240)
+ alignways (34977)
+ apache-commons (35092)
+ apache-http (34908)
+ auto_tools (73)
+ buildings_tools (34982)
+ conflation (0.6.4)
+ ejml (35122)
+ geotools (35154)
+ gridify (1556174547)
+ imagery_offset_db (34908)
+ jaxb (35014)
+ jna (34908)
+ jts (35122)
+ log4j (34908)
+ measurement (35051)
+ opendata (35156)
+ openvisible (34908)
+ pdfimport (34977)
+ reltoolbox (34977)
+ reverter (35084)
+ terracer (34977)
+ undelete (34977)
+ utilsplugin2 (35098)
+ waypoint_search (34977)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/Iranian_Preset&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/BicycleJunction&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/contact(socialnetworks_IMs)&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/BuildingPreset&zip=1
+ https://github.com/kendzi/Simple3dBuildingsPreset/releases/download/0.9_2018-05-08/s3db-preset.zip

Map paint styles:
- https://josm.openstreetmap.de/josmfile?page=Styles/Admin_Boundaries&zip=1
- https://github.com/bastik/mapcss-tools/raw/osm/mapnik2mapcss/osm-results/mapnik.zip

Last errors/warnings:
- E: Failed to locate image ''
- W: No configuration settings found.  Using hardcoded default values for all pools.
- E: Thread main-worker-0 raised java.util.concurrent.RejectedExecutionException: Task org.openstreetmap.josm.plugins.mapillary.oauth.UploadUtils$SequenceUploadRunnable$$Lambda$505/13221019@1f15ed9 rejected from java.util.concurrent.ThreadPoolExecutor@db6aad[Running, pool size = 8, active threads = 8, queued tasks = 15, completed tasks = 0]
- E: Handled by bug report queue: java.util.concurrent.RejectedExecutionException: Task org.openstreetmap.josm.plugins.mapillary.oauth.UploadUtils$SequenceUploadRunnable$$Lambda$505/13221019@1f15ed9 rejected from java.util.concurrent.ThreadPoolExecutor@db6aad[Running, pool size = 8, active threads = 8, queued tasks = 15, completed tasks = 0]
- E: Thread main-worker-1 raised java.util.concurrent.RejectedExecutionException: Task org.openstreetmap.josm.plugins.mapillary.oauth.UploadUtils$SequenceUploadRunnable$$Lambda$505/13221019@312c23 rejected from java.util.concurrent.ThreadPoolExecutor@13be140[Running, pool size = 8, active threads = 8, queued tasks = 15, completed tasks = 0]
- E: Handled by bug report queue: java.util.concurrent.RejectedExecutionException: Task org.openstreetmap.josm.plugins.mapillary.oauth.UploadUtils$SequenceUploadRunnable$$Lambda$505/13221019@312c23 rejected from java.util.concurrent.ThreadPoolExecutor@13be140[Running, pool size = 8, active threads = 8, queued tasks = 15, completed tasks = 0]


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: main-worker-1 (88)
java.util.concurrent.RejectedExecutionException: Task org.openstreetmap.josm.plugins.mapillary.oauth.UploadUtils$SequenceUploadRunnable$$Lambda$505/13221019@312c23 rejected from java.util.concurrent.ThreadPoolExecutor@13be140[Running, pool size = 8, active threads = 8, queued tasks = 15, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at org.openstreetmap.josm.plugins.mapillary.oauth.UploadUtils$SequenceUploadRunnable.lambda$run$2(UploadUtils.java:109)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.openstreetmap.josm.plugins.mapillary.oauth.UploadUtils$SequenceUploadRunnable.run(UploadUtils.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
}}}
```

</details>

Mapillary plugin and JOSM are up-to-date and I'm logged-in. It's the first time I'm trying to upload using JOSM.

**Comment by tsmock** [comment]
@GhostFoxSledgehammer significantly modified the code for the upload functionality during the Google Summer of Code. Is this fixed?

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> @GhostFoxSledgehammer significantly modified the code for the upload functionality during the Google Summer of Code. Is this fixed?

No, image upload part hasn't been touched by me, but looking at the code I think it will give error whenever images size is more than 23. 

`this.ex = new ThreadPoolExecutor(8, 8, 25, TimeUnit.SECONDS, new ArrayBlockingQueue<>(15));`

`uploadImages.forEach(img -> ex.execute(() -> upload(img, uuid)));`

**Comment by tsmock** [comment]
OK. I thought you had touched the upload code during GSoC. I was wrong.

Anyway, it is a should be a simple fix. The root issue is that the queue for the worker cannot expand, so when additional tasks are added and older tasks haven't finished yet, there will be an exception (since the queue had a set size of 15).
