### ISSUE TITLE
Unexpected exception when filtering images

### ISSUE THREAD

**Issue by richlv** [JOSM/Mapillary#145]
Not sure about reproducibility, but used the Mapillary image filter (by time, had both "Not older than" and "Start" populated)

```
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-11-21 14:56:29 +0100 (Sat, 21 Nov 2020)
Build-Date:2020-11-22 02:30:52
Revision:17329
Relative:URL: ^/trunk

Identification: JOSM/1.5 (17329 en_GB) Mac OS X 10.15.7
OS Build number: Mac OS X 10.15.7 (19H15)
Memory Usage: 1985 MB / 1985 MB (582 MB allocated, but free)
Java version: 1.8.0_271-b09, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Look and Feel: com.apple.laf.AquaLookAndFeel
Screen: Display 69733382 1680x1050 (scaling 1.0x1.0)
Maximum Screen Size: 1680x1050
Best cursor sizes: 16x16 -> 16x16, 32x32 -> 32x32
VM arguments: [-Djnlp.application.href=https://josm.openstreetmap.de/download/josm.jnlp, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlp.tk=awt, -Djnlpx.jvm=<java.home>/bin/java, -Djnlpx.splashport=-1, -Djnlpx.home=<java.home>/bin, -Djnlpx.remove=false, -Djnlpx.offline=false, -Djnlpx.relaunch=true, -Djnlpx.session.data=/var/folders/nl/flqxqsmj5q963r7tcnfrdt3c0000gn/T/session7776428352324607955, -Djnlpx.heapsize=-1,2147483648, -Djava.security.policy=file:<java.home>/lib/security/javaws.policy, -DtrustProxy=true, -Djnlpx.origFilenameArg=/Users/richlv/Library/Application Support/Oracle/Java/Deployment/cache/6.0/56/1ee8cfb8-72e8e992, -Dsun.awt.warmup=true, -Djava.security.manager]
Dataset consistency test: No problems found

Plugins:
+ InfoMode (35543)
+ Mapillary (1.5.27)
+ PicLayer (2a9aa7a)
+ apache-commons (35524)
+ apache-http (35589)
+ ejml (35458)
+ geotools (35458)
+ imagery_offset_db (35640)
+ javafx-osx (35458)
+ jaxb (35543)
+ jna (35458)
+ jts (35458)
+ measurement (35640)
+ opendata (35640)
+ pbf
+ photo_geotagging (35640)
+ reverter (35640)
+ utilsplugin2 (35640)

Map paint styles:
- /Users/richlv/Desktop/ChangeFontSize.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_Streets&zip=1

Last errors/warnings:
- 76681.195 W: Could not read from URL https://a.mapillary.com/v3/image_detections?client_id=UTZhSnNFdGpxSEFFREUwb01GYzlXZzpjNGViMzQxMTIzMjY0MjZm&bbox=24.3185391%2C57.0809221%2C24.3211455%2C57.0820022&layers=trafficsigns&sort_by=key!: java.io.IOException: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: java.io.IOException: stream is closed
- 76710.771 W: Could not read from URL https://a.mapillary.com/v3/images?client_id=UTZhSnNFdGpxSEFFREUwb01GYzlXZzpjNGViMzQxMTIzMjY0MjZm&_next_page_token=eyJhZnRlciI6WzE1OTEzNzc4NzYwMDAsInFCSVJycFlpWFNETEctZUFrcUxvX0EiXX0%3D&bbox=24.3185391%2C57.0809221%2C24.3211455%2C57.0820022!: java.io.IOException: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: java.io.IOException: stream is closed
- 77018.953 W: Could not read from URL https://a.mapillary.com/v3/image_detections?layers=trafficsigns&client_id=UTZhSnNFdGpxSEFFREUwb01GYzlXZzpjNGViMzQxMTIzMjY0MjZm&sort_by=key&bbox=24.3185055%2C57.0810063%2C24.3210697%2C57.0816418&_next_page_token=eyJpZCI6IjZtOWk2dWhfeElsZ0xNSmpqcElSVWciLCJhZnRlciI6WyI2ZzVLVGN4NUhVQXFaNGJjUTY0emtnIl0sIm9mZnNldCI6NH0%3D!: java.io.IOException: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: java.io.IOException: stream is closed
- 77019.577 W: Could not read from URL https://a.mapillary.com/v3/image_detections?layers=trafficsigns&client_id=UTZhSnNFdGpxSEFFREUwb01GYzlXZzpjNGViMzQxMTIzMjY0MjZm&sort_by=key&bbox=24.3181758%2C57.0809439%2C24.3207822%2C57.082024&_next_page_token=eyJpZCI6IjVEbGlJRXc3NGVpYkhMNXd2cEcwMmMiLCJhZnRlciI6WyI1QVo2UWxxcFN3OVlha2N6aUFuNXp3Il0sIm9mZnNldCI6Mn0%3D!: java.io.IOException: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: java.io.IOException: stream is closed
- 77024.551 W: Could not read from URL https://a.mapillary.com/v3/image_detections?client_id=UTZhSnNFdGpxSEFFREUwb01GYzlXZzpjNGViMzQxMTIzMjY0MjZm&bbox=24.3189512%2C57.0800128%2C24.3216142%2C57.0811164&layers=trafficsigns&sort_by=key!: java.io.IOException: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: javax.json.JsonException: I/O error while auto-detecting the encoding of stream. Cause: java.io.IOException: stream is closed
- 124223.108 E: Handled by bug report queue: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
- 124241.028 W: java.net.SocketTimeoutException: Read timed out. Cause: java.net.SocketTimeoutException: Read timed out
- 124241.029 W: java.net.SocketTimeoutException: Read timed out. Cause: java.net.SocketTimeoutException: Read timed out
- 124241.080 W: java.net.SocketTimeoutException: Read timed out. Cause: java.net.SocketTimeoutException: Read timed out
- 124244.442 W: Warning - <html>JOSM could not find information about the following plug-ins:<ul><li>imagery_offset_db</li><li>InfoMode</li><li>apache-commons</li><li>geotools</li><li>javafx-osx</li><li>opendata</li><li>jts</li><li>Mapillary</li><li>ejml</li><li>reverter</li><li>measurement</li><li>jaxb</li><li>utilsplugin2</li><li>pbf</li><li>photo_geotagging</li><li>jna</li><li>PicLayer</li><li>apache-http</li></ul>The plug-ins are not going to be loaded.</html>


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-2 (31) of javawsApplicationThreadGroup
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
	at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
	at java.time.LocalDate.of(LocalDate.java:267)
	at org.openstreetmap.josm.plugins.datepicker.impl.DatePickerJDatePicker.getDate(DatePickerJDatePicker.java:56)
	at org.openstreetmap.josm.plugins.mapillary.gui.dialog.MapillaryFilterDialog.refresh(MapillaryFilterDialog.java:316)
	at org.openstreetmap.josm.plugins.mapillary.gui.dialog.MapillaryFilterDialog$UpdateAction.actionPerformed(MapillaryFilterDialog.java:461)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tsmock** [comment]
Thank you for reporting this. This was actually _very_ reproducible. I'm actually surprised no one reported it before now. The only caveat is that this bug only appears on January and December dates.

I didn't see this bug until yesterday, but if you don't get some kind of response quickly (2-3 days or so), feel free to mention me (so @tsmock ). Or you can file a bug on JOSM trac and set the component to `Plugin Mapillary`, and I'll see it there.

**Comment by richlv** [comment]
Which is the preferred issue tracker for the plugin?

**Comment by tsmock** [comment]
Either works. I check GitHub every so often (usually around the time I'm doing a release) and fix bugs at that time. With JOSM Trac, I get notified immediately, and depending upon the severity and the number of people affected, I may fix it ASAP or when I have some spare time.

So whichever one you are more comfortable using. Just note that when https://josm.openstreetmap.de/ticket/16871 / https://josm.openstreetmap.de/ticket/16857 are closed, it is likely that (most? all?) JOSM plugins will be moving to a JOSM GitLab instance, so JOSM trac might be a better long term.

**Comment by richlv** [comment]
Thanks, will leave this one here and for any potential future reports go with trac (or Gitlab, when/if that migration happens :) ).
