### ISSUE TITLE
Crash: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null

### ISSUE THREAD

**Issue by Talkless** [JOSM/Mapillary#185]
When I enable Mapillary layer, and start to do "something" in JOSM (17833), I get suggestion to turn off Mapillary plugin due to some issues.

This is full report:
```
Revision:17833
Is-Local-Build:false
Build-Date:1970-01-05 09:32:38
Debian-Release:0.0.svn17833+dfsg-1~exp1
Build-Name:Debian

Identification: JOSM/1.5 (17833 Debian lt) Linux Debian GNU/Linux 11 (bullseye)
Memory Usage: 698 MB / 3926 MB (290 MB allocated, but free)
Java version: 15.0.3+3-Debian-1, Debian, OpenJDK 64-Bit Server VM
Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
Screen: :0.0 1920×1080 (scaling 1.00×1.00)
Maximum Screen Size: 1920×1080
Best cursor sizes: 16×16→16×16, 32×32→32×32
Environment variable LANG: lt_LT.UTF-8
System property file.encoding: UTF-8
System property sun.jnu.encoding: UTF-8
Locale info: lt_LT
Numbers with default locale: 1234567890 -> 1234567890
Desktop environment: KDE
Java ATK Wrapper package: libatk-wrapper-java:all-0.38.0-2
libcommons-compress-java: libcommons-compress-java:all-1.20-1
libcommons-logging-java: libcommons-logging-java:all-1.2-2
fonts-noto: fonts-noto:all-20201225-1
liboauth-signpost-java: liboauth-signpost-java:all-1.2.1.2-3
VM arguments: [-Djosm.restart=true, -Djava.net.useSystemProxies=true]
Dataset consistency test: No problems found

Plugins:
+ KartaView (374)
+ Mapillary (1.5.37.6)
+ OpeningHoursEditor (35640)
+ RoadSigns (35640)
+ apache-commons (35524)
+ apache-http (35589)
+ buildings_tools (35740)
+ editgpx (35562)
+ javafx-unixoid (35655)
+ jna (35662)
+ photo_geotagging (35738)
+ photoadjust (35770)
+ reltoolbox (35640)
+ tageditor (35640)
+ terracer (35640)
+ turnlanes-tagging (288)
+ utilsplugin2 (35691)

Map paint styles:
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1

Last errors/warnings:
- 00045.272 W: Region [userProfile_BLOCK_v2] : Problem verifying disk.
- 00099.338 E: Unknown detection "human--person--individual"
- 00225.417 E: Unknown detection "human--person--individual"
- 00229.164 E: Unknown detection "human--person--individual"
- 00229.165 E: Unknown detection "human--person--individual"
- 00229.606 E: Handled by bug report queue: java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null
- 00229.646 E: Handled by bug report queue: java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null
- 00229.682 E: Handled by bug report queue: java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null
- 00230.047 E: Handled by bug report queue: java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null
- 00230.912 E: Handled by bug report queue: java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null



=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (21) of main
java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:240)
	at org.openstreetmap.josm.plugins.mapillary.model.MapObject.getIcon(MapObject.java:87)
	at org.openstreetmap.josm.plugins.mapillary.gui.MapillaryImageDisplay.paintNonPano(MapillaryImageDisplay.java:641)
	at org.openstreetmap.josm.plugins.mapillary.gui.MapillaryImageDisplay.paintDetections(MapillaryImageDisplay.java:591)
	at org.openstreetmap.josm.plugins.mapillary.gui.MapillaryImageDisplay.paintComponent(MapillaryImageDisplay.java:510)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by tsmock** [comment]
(a) Update JOSM (17833 -> 17919)
(b) Update the plugins -- I fixed this issue already, but it does require the latest version of JOSM. At this time I'm disinclined to port fixes back to old plugin versions, since I don't know _when_ Mapillary is shutting down the v3 API, which would kill those versions anyway. I'm assuming sometime this month, but for other API users I'm hoping for six months.

**Comment by Talkless** [comment]
> (a) Update JOSM (17833 -> 17919)

Thanks, it did the trick. I've discovered that _there is_ 17919 version in Debian Experimental repository.
