### ISSUE TITLE
Smart mode error

### ISSUE THREAD

**Issue by angoca** [JOSM/Mapillary#186]
When I enable the smart mode, I received an error:
```
SEVERE: Handled by bug report queue: java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException
	at org.openstreetmap.josm.data.osm.BBox$Immutable.set(BBox.java:482)
	at org.openstreetmap.josm.data.osm.BBox.add(BBox.java:150)
	at org.openstreetmap.josm.data.osm.BBox.addPrimitive(BBox.java:188)
	at org.openstreetmap.josm.plugins.mapillary.gui.dialog.TrafficSignFilter.lambda$hideNearbyAddableObjs$34(TrafficSignFilter.java:350)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.openstreetmap.josm.plugins.mapillary.gui.dialog.TrafficSignFilter.lambda$hideNearbyAddableObjs$35(TrafficSignFilter.java:347)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.openstreetmap.josm.plugins.mapillary.gui.dialog.TrafficSignFilter.hideNearbyAddableObjs(TrafficSignFilter.java:341)
	at org.openstreetmap.josm.plugins.mapillary.gui.dialog.TrafficSignFilter.smartEditMode(TrafficSignFilter.java:404)
	at org.openstreetmap.josm.plugins.mapillary.gui.dialog.TrafficSignFilter.lambda$new$1(TrafficSignFilter.java:114)
	at javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2050)
	at javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2355)
	at javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:455)
	at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:272)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:289)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
I am using the 2.0 alpha 23 dirty.

**Comment by tsmock** [comment]
Thank you for reporting this bug. Fixed in 78ab84ae0adbba545a8ea2691781fe612cb7266f.
